version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    networks:
      - appnet

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - appnet

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/uploads:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
